[default]
# ORDER OF ENCODINGS TO BE USED
# DO NOT CHANGE THIS VALUE UNLESS YOU KNOW WHAT YOU'RE DOING
ENCODINGS_TO_TRY = ["utf-8", "latin1", "iso-8859-1"]
DEFAULT_VALUE_FOR_MISSING = "MIGRAÇÃO"
FIELD_MAPPINGS = { "NOME": "Nome", "CPF CNPJ": "CPF_CNPJ", "DATA DE NASCIMENTO": "DataNascimento" }
DATE_COLUMNS = ["DATA DE NASCIMENTO"]
CPF_CNPJ_COLUMN = "CPF CNPJ"

